import Head from "next/head";
import Skills from "../components/Skills";

// import Image Component from "next/image";
import Image from "next/image";

// Animation
import Fade from "react-reveal/Fade";

// Icons
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";

// Project Assets
import deved from "../public/assets/devedwave.png";
import AboutMe from "../components/AboutMe";
import ContactMe from "../components/ContactMe";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Diven I React Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-50 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl">Hello</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 px-4 py-2 border-none rounded-md ml-8"
                  href="./Resume"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Diven Khatri
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">React Developer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 max-w-5xl mx-auto">
              React developer specializing in building (and occasionally
              designing) exceptional digital experiences. Currently, I&apos;M
              focused on building responsive web and mobile applications
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <a href="https://www.linkedin.com/in/diven-khatri-0199a6213/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/dewo952?tab=repositories">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} alt="/" fill objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <Fade bottom>
            <AboutMe />
          </Fade>
          <Fade bottom>
            <Skills />
          </Fade>
          <Fade bottom>
            <Projects />
          </Fade>
          <Fade bottom>
            <ContactMe />
          </Fade>
        </section>
      </main>
    </div>
  );
}
